# Generated by Django 5.2.2 on 2025-08-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='file_name',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ml_models/'),
        ),
    ]
