# Generated by Django 5.2.2 on 2025-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_mlmodel_file_name_mlmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
